apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
  labels:
    app: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - image: "{{ image_id }}"
        name: kubernetes-configmap-reload
        ports:
        - containerPort: 8080
          name: http
